# Chapter 1: Quiz {-}


Note: The pull-down menu for selecting an answer turns green after selecting the correct answer. 


::: {.exercise}
The start point for a statistical analysis should be?

1. A data set with many variables that allows testing many different hypotheses
2. A clearly specified research question 
3. The believe that my hypothesis is probably true 

Answer: `r webex::mcq(c("1", answer = "2", "3"))`
:::

::: {.exercise}
Which of the following is NOT one of the steps in the research process?

1. Research Question
2. Operationalisation and data collection 
3. Statistical analysis 
4. Responding to emails 
5. Communication of the results 

Answer: `r webex::mcq(c("1", "2", "3", answer = "4", "5"))`
:::

::: {.exercise}
What is NOT part of the operationalisation?

1. Hypothetico-deductive method
2. Specifying which tasks or questionnaires will be used
3. Transformation of a research question into empirical and statistical hypothesis 
4. Deciding for which variables data will be collected

Answer: `r webex::mcq(c(answer = "1", "2", "3", "4"))`
:::

::: {.exercise}
What is the main reason why we need statistics?

1. To prove/confirm a theory 
2. To test whether the data we collected provide evidence for the empirical hypothesis 
3. To publish papers in high-impact journals 

Answer: `r webex::mcq(c("1", answer = "2", "3"))`
:::

::: {.exercise}
What is an epistemic gap?

1. The difference between what we want to know and what we can know 
2. A specific outcome predicted by a theory 
3. A mathematically formalized cognitive theory 

Answer: `r webex::mcq(c(answer ="1", "2", "3"))`
:::


::: {.exercise}
Underdetermination of theory by data suggests that:

1. Every specific hypothesis or theory is false or will eventually shown to be false
2. We need hypotheses to answer research questions 
3. No single data sets unambiguously supports a specific hypothesis or theory 

Answer: `r webex::mcq(c("1", "2", answer = "3"))`
:::

::: {.exercise}
When can a researcher assume that the data support the empirical prediction?  

1. When the data descriptively supports the empirical prediction
2. When there are no epistemic gaps 
3. When the estimated signal is large given the estimated level of noise
4. When the estimated level of noise is smaller than a pre-specified threshold

Answer: `r webex::mcq(c("1", "2", answer = "3", "4"))`
:::

::: {.exercise}
What can we conclude if a statistical analysis provides strong support for our empirical hypothesis? 

1. Our research question is true or probably true
2. Our empirical hypothesis is true or probably true 
3. It is unlikely that an alternative explanation could explain the results
4. None of the above

Answer: `r webex::mcq(c("1", "2", "3", answer = "4"))`
:::



